### ISSUE TITLE
NullPointerException at VariablesReplaceBuilder.replaceFileContent (VariablesReplaceBuilder.java:55) on Jenkins 2.277.3

### ISSUE THREAD

**Issue by mivola** [JeeDay/variables-replace#12]
Hi,

I really like this plugin but since the last Jenkins upgrade (to 2.277.3) I see an exception in the log when executing the plugin in a new job:

ERROR: Build step failed with exception
java.lang.NullPointerException
	at com.jeeday.jenkins.variablesReplace.VariablesReplaceBuilder.replaceFileContent(VariablesReplaceBuilder.java:55)
	at com.jeeday.jenkins.variablesReplace.VariablesReplaceBuilder.perform(VariablesReplaceBuilder.java:50)
	at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:123)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:80)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:803)
	at hudson.model.Build$BuildExecution.build(Build.java:197)
	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:513)
	at hudson.model.Run.execute(Run.java:1907)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)

Furthermore I have the feeling the UI is a bit odd when adding "Variables Replace" as a new build step:
![image](https://user-images.githubusercontent.com/743342/116191754-291c0080-a72d-11eb-9fad-b550a1e7e1b7.png)

i.e. I see 3 sections for "Name" & "Value" where I would only expect one.

And (maybe totally unrelated) I have one existing job which seems broken right after the "Variables Replace" plugin:
![image](https://user-images.githubusercontent.com/743342/116192007-8fa11e80-a72d-11eb-857d-1a1ae97c87b8.png)

i.e. the UI seems strange and I cant save/update this job...

Any suggestions?

Thanks a lot!
Michael

**Comment by Baccanno** [comment]
I'm having issues as well in 2.289.1

Looks like there are some issues in the html structure (repeatable.js)

That's a shame I can't find any similar plugin
